### ISSUE TITLE
Failed to activate the apicloud-autocomplete package

### ISSUE THREAD

**Issue by HomlesZhao** [apicloudcom/apicloud_autocomplete_atom#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [apicloud-autocomplete](https://github.com/apicloudcom/apicloud_autocomplete_atom) package 0.0.2

### Stack Trace

Failed to activate the apicloud-autocomplete package

```
At Cannot find module 'normalizr'

Error: Cannot find module 'normalizr'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/apicloud_autocomplete_atom/lib/modules.js:2:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/apicloud_autocomplete_atom/lib/provider.js:4:34)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/apicloud_autocomplete_atom/lib/apicloud-autocomplete.js:7:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
 14x -0:44.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
apicloud-autocomplete 0.0.2 
quick-highlight 0.8.1 
atom-react-native-autocomplete 0.0.27 
node_modules undefined 
open-in-browser 0.4.7 
seti-ui 1.6.1 
```

**Comment by ios122** [comment]
重新安装 apicloud-autocomplete 或者 手动再 ~/.atom/packages 目录下的 apicloud-autocomplete  文件夹,执行

```npm i normalizr ```   猜测应该是安装插件的过程中,意外中断了.
